# Terraform configuration for credit-risk
# Generated by Geronimo

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Backend configuration - customize for your environment
  # backend "s3" {
  #   bucket         = "your-terraform-state-bucket"
  #   key            = "credit-risk/terraform.tfstate"
  #   region         = "us-east-1"
  #   encrypt        = true
  #   dynamodb_table = "terraform-locks"
  # }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "credit-risk"
      Environment = var.environment
      ManagedBy   = "terraform"
      Generator   = "geronimo"
    }
  }
}

# Data sources for VPC networking
data "aws_vpc" "main" {
  id = var.vpc_id
}

data "aws_subnets" "private" {
  filter {
    name   = "vpc-id"
    values = [var.vpc_id]
  }

  tags = {
    Type = "private"
  }
}
